name    'counsyl-python'
version '0.9.0'
source  'git://github.counsyl.com/dev/puppet-python.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Installs the Python language runtime'
description 'Installs the Python language runtime'
project_page 'https://github.counsyl.com/dev/puppet-python'

dependency 'counsyl/sys', '>= 0.9.0'
