name    'counsyl-python'
version '1.0.0'
source 'git://github.counsyl.com/justin/counsyl-python.git'
author 'counsyl'
license 'Apache License, Version 2.0'
summary 'Installs the Python language runtime'
description 'Installs the Python language runtime'
project_page 'https://github.counsyl.com/justin/counsyl-python'

dependency 'counsyl/sys', '>= 1.0.0'
